#### Reading CSV file

In [1]:
import pandas as pd
dataset=pd.read_csv(r"C:\Users\Bhagya\data_cleaning\GlobalWeatherRepository.csv")
dataset.head(5)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,16-05-2024 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,16-05-2024 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,16-05-2024 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,16-05-2024 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,16-05-2024 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

#### Checking number of columns, NULL values

In [2]:
dataset.info()
print("\n\nChecking Number of Nulls in each column: \n")
dataset.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96850 entries, 0 to 96849
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       96850 non-null  object
 1   location_name                 96850 non-null  object
 2   latitude                      96850 non-null  float64
 3   longitude                     96850 non-null  float64
 4   timezone                      96850 non-null  object
 5   last_updated_epoch            96850 non-null  int64
 6   last_updated                  96850 non-null  object
 7   temperature_celsius           96850 non-null  float64
 8   temperature_fahrenheit        96850 non-null  float64
 9   condition_text                96850 non-null  object
 10  wind_mph                      96850 non-null  float64
 11  wind_kph                      96850 non-null  float64
 12  wind_degree                   96850 non-null  int64
 13  wind_direction                96850 non-null  object
 14  pressure_mb                   96850 non-null  int64
 15  pressure_in                   96850 non-null  float64
 16  precip_mm                     96850 non-null  float64
 17  precip_in                     96850 non-null  float64
 18  humidity                      96850 non-null  int64
 19  cloud                         96850 non-null  int64
 20  feels_like_celsius            96850 non-null  float64
 21  feels_like_fahrenheit         96850 non-null  float64
 22  visibility_km                 96850 non-null  float64
 23  visibility_miles              96850 non-null  int64
 24  uv_index                      96850 non-null  float64
 25  gust_mph                      96850 non-null  float64
 26  gust_kph                      96850 non-null  float64
 27  air_quality_Carbon_Monoxide   96850 non-null  float64
 28  air_quality_Ozone             96850 non-null  float64
 29  air_quality_Nitrogen_dioxide  96850 non-null  float64
 30  air_quality_Sulphur_dioxide   96850 non-null  float64
 31  air_quality_PM2.5             96850 non-null  float64
 32  air_quality_PM10              96850 non-null  float64
 33  air_quality_us-epa-index      96850 non-null  int64
 34  air_quality_gb-defra-index    96850 non-null  int64
 35  sunrise                       96850 non-null  object
 36  sunset                        96850 non-null  object
 37  moonrise                      96850 non-null  object
 38  moonset                       96850 non-null  object
 39  moon_phase                    96850 non-null  object
 40  moon_illumination             96850 non-null  int64
dtypes: float64(21), int64(9), object(11)
memory usage: 30.3+ MB


Checking Number of Nulls in each column:

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

#### Checking Number of Zero's in each column

In [3]:
(dataset==0).sum()

country                             0
location_name                       0
latitude                            0
longitude                           0
timezone                            0
last_updated_epoch                  0
last_updated                        0
temperature_celsius                49
temperature_fahrenheit              3
condition_text                      0
wind_mph                            0
wind_kph                            0
wind_degree                         0
wind_direction                      0
pressure_mb                         0
pressure_in                         0
precip_mm                       64260
precip_in                       81450
humidity                            0
cloud                           24585
feels_like_celsius                 50
feels_like_fahrenheit               2
visibility_km                     581
visibility_miles                 1000
uv_index                        17934
gust_mph                            0
gust_kph                            0
air_quality_Carbon_Monoxide         0
air_quality_Ozone                 572
air_quality_Nitrogen_dioxide     2706
air_quality_Sulphur_dioxide      1664
air_quality_PM2.5                   0
air_quality_PM10                    0
air_quality_us-epa-index            0
air_quality_gb-defra-index          0
sunrise                             0
sunset                              0
moonrise                            0
moonset                             0
moon_phase                          0
moon_illumination                4148
dtype: int64

#### Cleaning 'Country' column

In [4]:
print(f"Number of unique country names: {dataset['country'].nunique()}")    
dataset['country'].unique()

Number of unique country names: 211

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Madagascar', 'Cape Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Comoros',
       'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
       'Czech Republic', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Swaziland', 'Ethiopia', 'Fiji Islands', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Vatican City', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrghyzstan', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Thailand', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Turkey', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles Islands',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'Sudan', 'Spain', 'Sri Lanka', 'Suriname', 'Sweden', 'Switzerland',
       'Syria', 'Tajikistan', 'Tanzania', 'Timor-Leste', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkmenistan', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe', 'Colombia',
       'USA United States of America', "Lao People's Democratic Republic",
       'Libya', 'Kosovo', 'Togo', 'Malásia', 'Komoren', 'كولومبيا',
       'Estonie', 'Гватемала', 'Inde', 'Letonia', 'Польша', 'Mexique',
       'Polônia', 'Marrocos', 'Турция', 'Saint-Vincent-et-les-Grenadines',
       'Saudi Arabien', 'Südkorea', 'Bélgica', 'Turkménistan', '火鸡',
       'Jemen', "Cote d'Ivoire"], dtype=object)

In [5]:
dataset['country']=dataset['country'].astype('string')
corrections = {
    "Kyrghyzstan": "Kyrgyzstan",
    "Komoren": "Comoros",
    "Inde": "India",
    "Malásia": "Malaysia",
    "Estonie": "Estonia",
    "Letonia": "Latvia",
    "Mexique": "Mexico",
    "Marrocos": "Morocco",
    "Saudi Arabien": "Saudi Arabia",
    "Südkorea": "South Korea",
    "Turkménistan": "Turkmenistan",
    "Jemen": "Yemen",
    "USA United States of America": "United States of America",
    "Saint-Vincent-et-les-Grenadines": "Saint Vincent and the Grenadines",
    "Bélgica": "Belgium",
    "Polônia": "Poland",
    "Lao People's Democratic Republic": "Laos",
    "Cote d'Ivoire": "Ivory Coast"
}
dataset['country']=dataset['country'].replace(corrections)
non_latin = {
    "كولومبيا": "Colombia",
    "Гватемала": "Guatemala",
    "Польша": "Poland",
    "Турция": "Turkey",
    "火鸡": "Turkey"
}
dataset['country'] = dataset['country'].replace(non_latin)
print(dataset['country'].unique().tolist())

['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Madagascar', 'Cape Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Comoros', 'Congo', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Swaziland', 'Ethiopia', 'Fiji Islands', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Vatican City', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Thailand', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Turkey', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles Islands', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'Sudan', 'Spain', 'Sri Lanka', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Timor-Leste', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe', 'Colombia', 'Laos', 'Libya', 'Kosovo', 'Togo', 'Ivory Coast']

#### Cleaning 'Location_name' column

In [6]:
print(f"Number unique location names: {dataset['location_name'].nunique()}")     #number of unique location names
print(dataset['location_name'].unique().tolist())

Number unique location names: 254
['Kabul', 'Tirana', 'Algiers', 'Andorra La Vella', 'Luanda', "Saint John's", 'Buenos Aires', 'Yerevan', 'Canberra', 'Vienna', 'Baku', 'Nassau', 'Manama', 'Dhaka', 'Bridgetown', 'Minsk', 'Brussels', 'Belmopan', 'Porto-Novo', 'Thimphu', 'Sucre', 'Sarajevo', 'Gaborone', 'Bras', 'Bandar Seri Begawan', 'Sofia', 'Ouagadougou', 'Bujumbura', 'Ivory', 'Praia', 'Phnom Penh', 'Yaounde', 'Ottawa', 'Bangui', "N'djamena", 'Santiago', 'Beijing', 'Bogot', 'Moroni', 'Brazzaville', 'San Juan', 'Zagreb', 'Havana', 'Nicosia', 'Prague', 'Kinshasa', 'Copenhagen', 'Djibouti', 'Roseau', 'Santo Domingo', 'Quito', 'Cairo', 'San Salvador', 'Malabo', 'Asmara', 'Tallinn', 'Mbabane', 'Addis Ababa', 'Suva', 'Helsinki', 'Paris', 'Libreville', 'Banjul', 'Tbilisi', 'Berlin', 'Accra', 'Athens', "Saint George's", 'Guatemala City', 'Conakry', 'Bissau', 'Georgetown', 'Port-Au-Prince', 'Vatican City', 'Tegucigalpa', 'Budapest', 'Grindavik', 'New Delhi', 'Jakarta', 'Tehran', 'Baghdad', 'Dublin', 'Jerusalem', 'Rome', 'Norman Gardens', 'Tokyo', 'Amman', 'Astana', 'Nairobi', 'Tarawa', 'Kuwait City', 'Bishkek', 'Laos', 'Riga', 'Beirut', 'Maseru', 'Monrovia', 'Nan', 'Vaduz', 'Vilnius', 'Luxembourg', 'Antananarivo', 'Lilongwe', 'Kuala Lumpur', 'Felidhoo', 'Bamako', 'Valletta', 'Majuro', 'Nouakchott', 'Port Louis', 'Mexico City', 'Palikir', 'Chi Chi Khvar', 'Monaco', 'Ulaanbaatar', 'Podgorica', 'Rabat', 'Maputo', 'Pathein', 'Windhoek', 'Yaren', 'Kathmandu', 'Amsterdam', 'Wellington', 'Managua', 'Niamey', 'Abuja', 'Pyongyang', 'Skopje', 'Oslo', 'Muscat', 'Islamabad', 'Meyungs', 'National', 'Panama City', 'Port Moresby', 'Pasto', 'Lima', 'Manila', 'Warsaw', 'Lisbon', 'Doha', 'Bucharest', 'Moscow', 'Kigali', 'Basseterre', 'Castries', 'Kingstown', 'Apia', 'San Marino', "'S Gravenstaffel", 'Riyadh', 'Dakar', 'Belgrade', 'Victoria', 'Freetown', 'Singapore', 'Bratislava', 'Ljubljana', 'Honiara', 'Mogadishu', 'Pretoria', 'Seoul', 'Juba', 'Madrid', 'Colombo', 'Khartoum', 'Paramaribo', 'Stockholm', 'Bern', 'Damascus', 'Dushanbe', 'Dodoma', 'Bangkok', 'Dili', 'Lom', 'Nuku`Aloia', 'Port Of Spain', 'Tunis', 'Ankara', 'Ashgabat', 'Funafuti', 'Kampala', 'Kyiv', 'Abu Dhabi', 'London', 'Washington Park', 'Montevideo', 'Tashkent', 'Port Vila', 'Caracas', 'Hanoi', 'Sanaa', 'Lusaka', 'Harare', 'Bafoussam', 'San Ignacio', 'Rangoon', 'Adkip', 'Carreria', "'S Gravenjansdijk", 'Washington Harbor', "'S Gravenjansdyk", 'Ngaoundere', 'Vestmannaeyjar', 'Port Royal', 'Dhidhdhoo', 'Yangon', 'Koror', 'Aurora', 'Ban Lom', 'Saint Petersburg', 'Sao Paulo', 'Mombasa', 'Phnum Penh', 'Douala', 'Bogota', 'Addis Abeba', 'Grenada', 'Reykjavik', 'New York', 'Kingston', 'Vientiane', 'Tripoli', 'Male', 'Ho Chi Minh City', 'Bali', 'Palau', 'Asuncion', 'Pristina', 'Melbourne', 'Surabaya', 'Lome', "Nuku'alofa", 'Ivory Ivory Ban', 'Beijing Shi', 'Costa Rica', 'New Guatemala', 'Kuwait', 'Mexico (Grupo Mexico)', 'Moldova', 'Morocco City', 'Kiyabo', 'City Of San Marino', 'Ar Riyadh', 'Krasnyy Turkmenistan', '#NAME?', 'Airai', 'Yamoussoukro', 'San Jose', 'Aguaray', 'S-Chanf', 'Garrapata', "'S-Gravenbrakel"]

In [7]:
dataset['location_name']=dataset['location_name'].astype('string')
dataset['location_name'] = dataset['location_name'].str.strip().str.title()
corrections = {
    "Bras": "Brasilia",
    "Bogot": "Bogota",
    "Phnum Penh": "Phnom Penh",
    "Addis Abeba": "Addis Ababa",
    "Rangoon": "Yangon",
    "Beijing Shi": "Beijing",
    "New Guatemala": "Guatemala City",
    "Mexico (Grupo Mexico)": "Mexico City",
    "Nuku`Aloia": "Nuku'alofa",
    "Ivory Ivory Ban": "Abidjan",
    "Ivory": "Abidjan",
    "Saint John'S": "Saint John's",
    "Saint George'S": "Saint George's",
    "Nuku`Alofa": "Nuku'alofa",
    "City Of San Marino": "San Marino",
    "Ar Riyadh": "Riyadh",
    "'S Gravenstaffel": "S-Gravenstaffel",
    "'S Gravenjansdijk": "S-Gravenjansdijk",
    "'S Gravenjansdyk": "S-Gravenjansdyk",
    "'S-Gravenbrakel": "S-Gravenbrakel",
    "Kiyabo": "Kyiv",
    '#Name?':'Istanbul'
}
dataset['location_name'] = dataset['location_name'].replace(corrections)
print(f"Number unique location names: {dataset['location_name'].nunique()}") 
print(dataset['location_name'].unique().tolist())

Number unique location names: 243
['Kabul', 'Tirana', 'Algiers', 'Andorra La Vella', 'Luanda', "Saint John's", 'Buenos Aires', 'Yerevan', 'Canberra', 'Vienna', 'Baku', 'Nassau', 'Manama', 'Dhaka', 'Bridgetown', 'Minsk', 'Brussels', 'Belmopan', 'Porto-Novo', 'Thimphu', 'Sucre', 'Sarajevo', 'Gaborone', 'Brasilia', 'Bandar Seri Begawan', 'Sofia', 'Ouagadougou', 'Bujumbura', 'Abidjan', 'Praia', 'Phnom Penh', 'Yaounde', 'Ottawa', 'Bangui', "N'Djamena", 'Santiago', 'Beijing', 'Bogota', 'Moroni', 'Brazzaville', 'San Juan', 'Zagreb', 'Havana', 'Nicosia', 'Prague', 'Kinshasa', 'Copenhagen', 'Djibouti', 'Roseau', 'Santo Domingo', 'Quito', 'Cairo', 'San Salvador', 'Malabo', 'Asmara', 'Tallinn', 'Mbabane', 'Addis Ababa', 'Suva', 'Helsinki', 'Paris', 'Libreville', 'Banjul', 'Tbilisi', 'Berlin', 'Accra', 'Athens', "Saint George's", 'Guatemala City', 'Conakry', 'Bissau', 'Georgetown', 'Port-Au-Prince', 'Vatican City', 'Tegucigalpa', 'Budapest', 'Grindavik', 'New Delhi', 'Jakarta', 'Tehran', 'Baghdad', 'Dublin', 'Jerusalem', 'Rome', 'Norman Gardens', 'Tokyo', 'Amman', 'Astana', 'Nairobi', 'Tarawa', 'Kuwait City', 'Bishkek', 'Laos', 'Riga', 'Beirut', 'Maseru', 'Monrovia', 'Nan', 'Vaduz', 'Vilnius', 'Luxembourg', 'Antananarivo', 'Lilongwe', 'Kuala Lumpur', 'Felidhoo', 'Bamako', 'Valletta', 'Majuro', 'Nouakchott', 'Port Louis', 'Mexico City', 'Palikir', 'Chi Chi Khvar', 'Monaco', 'Ulaanbaatar', 'Podgorica', 'Rabat', 'Maputo', 'Pathein', 'Windhoek', 'Yaren', 'Kathmandu', 'Amsterdam', 'Wellington', 'Managua', 'Niamey', 'Abuja', 'Pyongyang', 'Skopje', 'Oslo', 'Muscat', 'Islamabad', 'Meyungs', 'National', 'Panama City', 'Port Moresby', 'Pasto', 'Lima', 'Manila', 'Warsaw', 'Lisbon', 'Doha', 'Bucharest', 'Moscow', 'Kigali', 'Basseterre', 'Castries', 'Kingstown', 'Apia', 'San Marino', 'S-Gravenstaffel', 'Riyadh', 'Dakar', 'Belgrade', 'Victoria', 'Freetown', 'Singapore', 'Bratislava', 'Ljubljana', 'Honiara', 'Mogadishu', 'Pretoria', 'Seoul', 'Juba', 'Madrid', 'Colombo', 'Khartoum', 'Paramaribo', 'Stockholm', 'Bern', 'Damascus', 'Dushanbe', 'Dodoma', 'Bangkok', 'Dili', 'Lom', "Nuku'alofa", 'Port Of Spain', 'Tunis', 'Ankara', 'Ashgabat', 'Funafuti', 'Kampala', 'Kyiv', 'Abu Dhabi', 'London', 'Washington Park', 'Montevideo', 'Tashkent', 'Port Vila', 'Caracas', 'Hanoi', 'Sanaa', 'Lusaka', 'Harare', 'Bafoussam', 'San Ignacio', 'Yangon', 'Adkip', 'Carreria', 'S-Gravenjansdijk', 'Washington Harbor', 'S-Gravenjansdyk', 'Ngaoundere', 'Vestmannaeyjar', 'Port Royal', 'Dhidhdhoo', 'Koror', 'Aurora', 'Ban Lom', 'Saint Petersburg', 'Sao Paulo', 'Mombasa', 'Douala', 'Grenada', 'Reykjavik', 'New York', 'Kingston', 'Vientiane', 'Tripoli', 'Male', 'Ho Chi Minh City', 'Bali', 'Palau', 'Asuncion', 'Pristina', 'Melbourne', 'Surabaya', 'Lome', "Nuku'Alofa", 'Costa Rica', 'Kuwait', 'Moldova', 'Morocco City', 'Krasnyy Turkmenistan', 'Istanbul', 'Airai', 'Yamoussoukro', 'San Jose', 'Aguaray', 'S-Chanf', 'Garrapata', 'S-Gravenbrakel']

#### Latitude Longitude cleaning

In [8]:
invalid_lat = ~dataset['latitude'].between(-90, 90)
invalid_lon = ~dataset['longitude'].between(-180, 180)

print(invalid_lat.sum())
print(invalid_lon.sum())

0
0

#### Time Zone cleaning

In [13]:
dataset['timezone'] = dataset['timezone'].str.strip()
#print(dataset['timezone'].unique().tolist())

#### last updated epoch

In [22]:
dataset['last_updated'] = pd.to_datetime(dataset['last_updated'], format='%d-%m-%Y %H:%M')
dataset['last_updated'] = dataset['last_updated'].dt.strftime('%d-%m-%Y %H:%M')
dataset.head(2)

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,16-05-2024 13:15,26.6,79.8,Partly Cloudy,8.3,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,16-05-2024 10:45,19.0,66.2,Partly cloudy,6.9,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55

#### temperature_celcius, temperature_fahrenheit, condition_text.

In [31]:
type(dataset['temperature_celsius'])
dataset = dataset.drop(columns=['temperature_fahrenheit'])

pandas.core.series.Series

In [32]:
dataset['temperature_celsius'] = dataset['temperature_celsius'].astype(float)
dataset['condition_text'] = dataset['condition_text'].astype('string').str.strip().str.title()
dataset.head(5)

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_mph,wind_kph,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,16-05-2024 13:15,26.6,Partly Cloudy,8.3,13.3,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,16-05-2024 10:45,19.0,Partly Cloudy,6.9,11.2,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,16-05-2024 09:45,23.0,Sunny,9.4,15.1,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,16-05-2024 10:45,6.3,Light Drizzle,7.4,11.9,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,16-05-2024 09:45,26.0,Partly Cloudy,8.1,13.0,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

#### Dropping redundant columns

In [35]:
redundant_cols = [ 'feels_like_fahrenheit',
    'wind_mph', 'pressure_in', 'precip_in', 'visibility_miles', 'gust_mph'
]
dataset = dataset.drop(columns=[col for col in redundant_cols if col in dataset.columns])
print(dataset.dtypes)

country                         string[python]
location_name                   string[python]
latitude                               float64
longitude                              float64
timezone                                object
last_updated                            object
temperature_celsius                    float64
condition_text                  string[python]
wind_kph                               float64
wind_degree                              int64
wind_direction                          object
pressure_mb                              int64
precip_mm                              float64
humidity                                 int64
cloud                                    int64
feels_like_celsius                     float64
visibility_km                          float64
uv_index                               float64
gust_kph                               float64
air_quality_Carbon_Monoxide            float64
air_quality_Ozone                      float64
air_quality_Nitrogen_dioxide           float64
air_quality_Sulphur_dioxide            float64
air_quality_PM2.5                      float64
air_quality_PM10                       float64
air_quality_us-epa-index                 int64
air_quality_gb-defra-index               int64
sunrise                                 object
sunset                                  object
moonrise                                object
moonset                                 object
moon_phase                              object
moon_illumination                        int64
dtype: object

#### changing data types

In [36]:
cols_to_string = [
    'wind_direction',
    'sunrise', 'sunset', 'moonrise', 'moonset', 'moon_phase'
]

for col in cols_to_string:
    if dataset[col].dtype != 'string':
        dataset[col] = dataset[col].astype('string')

print(dataset.dtypes)

country                         string[python]
location_name                   string[python]
latitude                               float64
longitude                              float64
timezone                                object
last_updated                            object
temperature_celsius                    float64
condition_text                  string[python]
wind_kph                               float64
wind_degree                              int64
wind_direction                  string[python]
pressure_mb                              int64
precip_mm                              float64
humidity                                 int64
cloud                                    int64
feels_like_celsius                     float64
visibility_km                          float64
uv_index                               float64
gust_kph                               float64
air_quality_Carbon_Monoxide            float64
air_quality_Ozone                      float64
air_quality_Nitrogen_dioxide           float64
air_quality_Sulphur_dioxide            float64
air_quality_PM2.5                      float64
air_quality_PM10                       float64
air_quality_us-epa-index                 int64
air_quality_gb-defra-index               int64
sunrise                         string[python]
sunset                          string[python]
moonrise                        string[python]
moonset                         string[python]
moon_phase                      string[python]
moon_illumination                        int64
dtype: object

#### Monthly averages

In [44]:
import pandas as pd
dataset['last_updated'] = pd.to_datetime(dataset['last_updated'], format='%d-%m-%Y %H:%M', errors='coerce')
dataset['year_month'] = dataset['last_updated'].dt.to_period('M')
num_cols = [
    'temperature_celsius', 'wind_kph', 'wind_degree', 'pressure_mb', 'precip_mm',
    'humidity', 'cloud', 'feels_like_celsius', 'visibility_km', 'uv_index',
    'gust_kph', 'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
    'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
    'air_quality_PM2.5', 'air_quality_PM10'
]
monthly_avg = dataset.groupby(['country', 'location_name', 'year_month'])[num_cols].mean().reset_index()
monthly_avg.to_csv("weather_data_monthly.csv", index=False)

#### Yearly Averages

In [45]:
import pandas as pd
dataset['last_updated'] = pd.to_datetime(dataset['last_updated'], errors='coerce')
dataset['year'] = dataset['last_updated'].dt.year
yearly_avg = dataset.groupby(['country', 'location_name', 'year']).mean(numeric_only=True).reset_index()
yearly_avg.to_csv("weather_yearly_avg.csv", index=False)

#### Seasonal Aggregation

In [46]:
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

dataset['month'] = dataset['last_updated'].dt.month
dataset['year'] = dataset['last_updated'].dt.year
dataset['season'] = dataset['month'].apply(get_season)
seasonal_avg = dataset.groupby(['country', 'location_name', 'year', 'season']).mean(numeric_only=True).reset_index()
seasonal_avg.to_csv("weather_seasonal_avg.csv", index=False)

In [48]:
dataset.to_csv("weather_daily.csv", index=False)